language: java
jdk:
  - oraclejdk7
addons:
  postgresql: "9.3"
before_install:
 - gem install compass
script: ant setupDB test dist
notifications:
  email:
      recipients:
        - bahmni@thoughtworks.com
      on_success: change
      on_failure: change
