INSERT INTO dhis2_test(test_name) VALUES('Hb'); 
INSERT INTO dhis2_test(test_name) VALUES('RBC'); 
INSERT INTO dhis2_test(test_name) VALUES('Platelates'); 
INSERT INTO dhis2_test(test_name) VALUES('WBC'); 
INSERT INTO dhis2_test(test_name) VALUES('DLC'); 
INSERT INTO dhis2_test(test_name) VALUES('ESR'); 
INSERT INTO dhis2_test(test_name) VALUES('PCV'); 
INSERT INTO dhis2_test(test_name) VALUES('MCV'); 
INSERT INTO dhis2_test(test_name) VALUES('MCHC/MCH'); 
INSERT INTO dhis2_test(test_name) VALUES('RDW'); 
INSERT INTO dhis2_test(test_name) VALUES('BT'); 
INSERT INTO dhis2_test(test_name) VALUES('CT'); 
INSERT INTO dhis2_test(test_name) VALUES('Retics'); 
INSERT INTO dhis2_test(test_name) VALUES('PBS'); 
INSERT INTO dhis2_test(test_name) VALUES('paracites'); 
INSERT INTO dhis2_test(test_name) VALUES('Special stain'); 
INSERT INTO dhis2_test(test_name) VALUES('PAS'); 
INSERT INTO dhis2_test(test_name) VALUES('Sickling test'); 
INSERT INTO dhis2_test(test_name) VALUES('Urine for...'); 
INSERT INTO dhis2_test(test_name) VALUES('APTT'); 
INSERT INTO dhis2_test(test_name) VALUES('Pt-INR'); 
INSERT INTO dhis2_test(test_name) VALUES('Blood group'); 
INSERT INTO dhis2_test(test_name) VALUES('RH type'); 
INSERT INTO dhis2_test(test_name) VALUES('BM'); 
INSERT INTO dhis2_test(test_name) VALUES('CSF'); 
INSERT INTO dhis2_test(test_name) VALUES('Spleen fluid'); 
INSERT INTO dhis2_test(test_name) VALUES('Aldehyde'); 
INSERT INTO dhis2_test(test_name) VALUES('MP total'); 
INSERT INTO dhis2_test(test_name) VALUES('HbA1c'); 
INSERT INTO dhis2_test(test_name) VALUES('Hb electro..'); 
INSERT INTO dhis2_test(test_name) VALUES('LE'); 
INSERT INTO dhis2_test(test_name) VALUES('ALC/AEC'); 
INSERT INTO dhis2_test(test_name) VALUES('FDP/dimer'); 
INSERT INTO dhis2_test(test_name) VALUES('FACVIII'); 
INSERT INTO dhis2_test(test_name) VALUES('FAC IX'); 
INSERT INTO dhis2_test(test_name) VALUES('Pregnancy test'); 
INSERT INTO dhis2_test(test_name) VALUES('ASO'); 
INSERT INTO dhis2_test(test_name) VALUES('CRP'); 
INSERT INTO dhis2_test(test_name) VALUES('RA factor'); 
INSERT INTO dhis2_test(test_name) VALUES('TPHA'); 
INSERT INTO dhis2_test(test_name) VALUES('ANA'); 
INSERT INTO dhis2_test(test_name) VALUES('DNA-ELISA'); 
INSERT INTO dhis2_test(test_name) VALUES('RPR/VDRL'); 
INSERT INTO dhis2_test(test_name) VALUES('CEA'); 
INSERT INTO dhis2_test(test_name) VALUES('CA-125'); 
INSERT INTO dhis2_test(test_name) VALUES('Ca19-9'); 
INSERT INTO dhis2_test(test_name) VALUES('Ca15.3'); 
INSERT INTO dhis2_test(test_name) VALUES('Torch IG-G/M'); 
INSERT INTO dhis2_test(test_name) VALUES('Measles-IG-G'); 
INSERT INTO dhis2_test(test_name) VALUES('Rubella-IGG'); 
INSERT INTO dhis2_test(test_name) VALUES('Echino-occus'); 
INSERT INTO dhis2_test(test_name) VALUES('Amino-biasis'); 
INSERT INTO dhis2_test(test_name) VALUES('PSA'); 
INSERT INTO dhis2_test(test_name) VALUES('Ferritine'); 
INSERT INTO dhis2_test(test_name) VALUES('Cystic-rcosis'); 
INSERT INTO dhis2_test(test_name) VALUES('bru-cella'); 
INSERT INTO dhis2_test(test_name) VALUES('Thyro-globin'); 
INSERT INTO dhis2_test(test_name) VALUES('protrin electrophorosis'); 
INSERT INTO dhis2_test(test_name) VALUES('B-HCG'); 
INSERT INTO dhis2_test(test_name) VALUES('RK 39'); 
INSERT INTO dhis2_test(test_name) VALUES('JE'); 
INSERT INTO dhis2_test(test_name) VALUES('Dengue'); 
INSERT INTO dhis2_test(test_name) VALUES('Rapid MP test'); 
INSERT INTO dhis2_test(test_name) VALUES('Mantoux test'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
INSERT INTO dhis2_test(test_name) VALUES('Sugar F'); 
INSERT INTO dhis2_test(test_name) VALUES('Sugar PP'); 
INSERT INTO dhis2_test(test_name) VALUES('SugarR'); 
INSERT INTO dhis2_test(test_name) VALUES('blood urea'); 
INSERT INTO dhis2_test(test_name) VALUES('Creatinine'); 
INSERT INTO dhis2_test(test_name) VALUES('Uric acid'); 
INSERT INTO dhis2_test(test_name) VALUES('S. protein'); 
INSERT INTO dhis2_test(test_name) VALUES('Albumin'); 
INSERT INTO dhis2_test(test_name) VALUES('Total Cholea'); 
INSERT INTO dhis2_test(test_name) VALUES('HD'); 
INSERT INTO dhis2_test(test_name) VALUES('TG'); 
INSERT INTO dhis2_test(test_name) VALUES('LDL'); 
INSERT INTO dhis2_test(test_name) VALUES('Calcium'); 
INSERT INTO dhis2_test(test_name) VALUES('Phosphorus'); 
INSERT INTO dhis2_test(test_name) VALUES('Amylase'); 
INSERT INTO dhis2_test(test_name) VALUES('Gamma GT'); 
INSERT INTO dhis2_test(test_name) VALUES('SGOT/AST'); 
INSERT INTO dhis2_test(test_name) VALUES('SGPT/ALT'); 
INSERT INTO dhis2_test(test_name) VALUES('Alk Phos'); 
INSERT INTO dhis2_test(test_name) VALUES('Billi-T'); 
INSERT INTO dhis2_test(test_name) VALUES('Billi-D'); 
INSERT INTO dhis2_test(test_name) VALUES('Sodium(Na)'); 
INSERT INTO dhis2_test(test_name) VALUES('Potassium'); 
INSERT INTO dhis2_test(test_name) VALUES('24 hr protein'); 
INSERT INTO dhis2_test(test_name) VALUES('24 hr urea'); 
INSERT INTO dhis2_test(test_name) VALUES('Creatinine clearance'); 
INSERT INTO dhis2_test(test_name) VALUES('Iron profile'); 
INSERT INTO dhis2_test(test_name) VALUES('others'); 
INSERT INTO dhis2_test(test_name) VALUES('ER'); 
INSERT INTO dhis2_test(test_name) VALUES('PR'); 
INSERT INTO dhis2_test(test_name) VALUES('G-FAP'); 
INSERT INTO dhis2_test(test_name) VALUES('s-100'); 
INSERT INTO dhis2_test(test_name) VALUES('vi-mentin'); 
INSERT INTO dhis2_test(test_name) VALUES('Cyto-keratin'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
INSERT INTO dhis2_test(test_name) VALUES('Gm stain'); 
INSERT INTO dhis2_test(test_name) VALUES('Blood'); 
INSERT INTO dhis2_test(test_name) VALUES('Urine'); 
INSERT INTO dhis2_test(test_name) VALUES('Body fluid'); 
INSERT INTO dhis2_test(test_name) VALUES('Swab'); 
INSERT INTO dhis2_test(test_name) VALUES('Stool'); 
INSERT INTO dhis2_test(test_name) VALUES('Water'); 
INSERT INTO dhis2_test(test_name) VALUES('Pus'); 
INSERT INTO dhis2_test(test_name) VALUES('Sputum'); 
INSERT INTO dhis2_test(test_name) VALUES('ENT'); 
INSERT INTO dhis2_test(test_name) VALUES('CSF'); 
INSERT INTO dhis2_test(test_name) VALUES('Body fluid AFB'); 
INSERT INTO dhis2_test(test_name) VALUES('Sputum AFB'); 
INSERT INTO dhis2_test(test_name) VALUES('Leprosy smear'); 
INSERT INTO dhis2_test(test_name) VALUES('Widal'); 
INSERT INTO dhis2_test(test_name) VALUES('Fungus'); 
INSERT INTO dhis2_test(test_name) VALUES('lepto-spira'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
INSERT INTO dhis2_test(test_name) VALUES('HIV'); 
INSERT INTO dhis2_test(test_name) VALUES('HAV'); 
INSERT INTO dhis2_test(test_name) VALUES('HBsAG'); 
INSERT INTO dhis2_test(test_name) VALUES('HCV'); 
INSERT INTO dhis2_test(test_name) VALUES('HEV'); 
INSERT INTO dhis2_test(test_name) VALUES('Western bolt'); 
INSERT INTO dhis2_test(test_name) VALUES('CD4 count'); 
INSERT INTO dhis2_test(test_name) VALUES('Viral load'); 
INSERT INTO dhis2_test(test_name) VALUES('others'); 
INSERT INTO dhis2_test(test_name) VALUES('Cytology'); 
INSERT INTO dhis2_test(test_name) VALUES('Pap'); 
INSERT INTO dhis2_test(test_name) VALUES('Sputum'); 
INSERT INTO dhis2_test(test_name) VALUES('Body fluid'); 
INSERT INTO dhis2_test(test_name) VALUES('FNAC'); 
INSERT INTO dhis2_test(test_name) VALUES('Histology'); 
INSERT INTO dhis2_test(test_name) VALUES('Bio-psy'); 
INSERT INTO dhis2_test(test_name) VALUES('Stool RE'); 
INSERT INTO dhis2_test(test_name) VALUES('Occult blood'); 
INSERT INTO dhis2_test(test_name) VALUES('Reducing sugar'); 
INSERT INTO dhis2_test(test_name) VALUES('Urine RE'); 
INSERT INTO dhis2_test(test_name) VALUES('Bile salts'); 
INSERT INTO dhis2_test(test_name) VALUES('Bile pigment'); 
INSERT INTO dhis2_test(test_name) VALUES('Urobi-linogen'); 
INSERT INTO dhis2_test(test_name) VALUES('porpho-bilinogen'); 
INSERT INTO dhis2_test(test_name) VALUES('Ace-tone'); 
INSERT INTO dhis2_test(test_name) VALUES('Chyle'); 
INSERT INTO dhis2_test(test_name) VALUES('Semen-analysis'); 
INSERT INTO dhis2_test(test_name) VALUES('Bence-jones prot'); 
INSERT INTO dhis2_test(test_name) VALUES('Sp. gravity'); 
INSERT INTO dhis2_test(test_name) VALUES('Micro albumin'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
INSERT INTO dhis2_test(test_name) VALUES('CPK-MB'); 
INSERT INTO dhis2_test(test_name) VALUES('CPK-NAC'); 
INSERT INTO dhis2_test(test_name) VALUES('LDH'); 
INSERT INTO dhis2_test(test_name) VALUES('Iso-trop-I'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
INSERT INTO dhis2_test(test_name) VALUES('T3'); 
INSERT INTO dhis2_test(test_name) VALUES('T4'); 
INSERT INTO dhis2_test(test_name) VALUES('TSH'); 
INSERT INTO dhis2_test(test_name) VALUES('Cortisol'); 
INSERT INTO dhis2_test(test_name) VALUES('a feto protein'); 
INSERT INTO dhis2_test(test_name) VALUES('LH'); 
INSERT INTO dhis2_test(test_name) VALUES('FSH'); 
INSERT INTO dhis2_test(test_name) VALUES('Pro lactine'); 
INSERT INTO dhis2_test(test_name) VALUES('Oestrogen'); 
INSERT INTO dhis2_test(test_name) VALUES('Progestrone'); 
INSERT INTO dhis2_test(test_name) VALUES('Testostrone'); 
INSERT INTO dhis2_test(test_name) VALUES('Vit. D'); 
INSERT INTO dhis2_test(test_name) VALUES('Drug nanlysiis'); 
INSERT INTO dhis2_test(test_name) VALUES('carbamazepine'); 
INSERT INTO dhis2_test(test_name) VALUES('Cyclosporine'); 
INSERT INTO dhis2_test(test_name) VALUES('Valporic acid'); 
INSERT INTO dhis2_test(test_name) VALUES('Phenny toin'); 
INSERT INTO dhis2_test(test_name) VALUES('Digo xine'); 
INSERT INTO dhis2_test(test_name) VALUES('Tacro limus'); 
INSERT INTO dhis2_test(test_name) VALUES('Others'); 
